error: uncaptured python exception, closing channel <asimap.server.IMAPClientHandler connected 10.0.1.236:57851 at 0x80617d5a8> (<class 'socket.error'>:[Errno 60] Operation timed out [/usr/local/lib/python2.7/asynchat.py|handle_read|115] [/usr/local/lib/python2.7/asyncore.py|recv|387] [/usr/local/lib/python2.7/ssl.py|recv|714] [/usr/local/lib/python2.7/ssl.py|read|608])
Traceback (most recent call last):
  File "/usr/local/libexec/asimapd.py", line 230, in <module>
    main()
  File "/usr/local/libexec/asimapd.py", line 211, in main
    asyncore.loop()
  File "/usr/local/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/local/lib/python2.7/asyncore.py", line 145, in poll
    r, w, e = select.select(r, w, e, timeout)
ValueError: filedescriptor out of range in select()
